version: '3.7'
services:
  rentx-db:
    image: postgres
    container_name: rentx-db
    restart: always
    ports:
      - '${DB_PORT}:5432'
    environment:
      - 'POSTGRES_USER=${DB_USERNAME}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_DB=${DB_DATABASE}'
    volumes:
      - pgdata:/data/postgres

  rentx-redis:
    image: redis:alpine
    ports:
      - '${REDIS_PORT}:6379'

  # rentx-api:
  #   build: .
  #   container_name: rentx-api
  #   ports:
  #     - 3333:3333
  #   volumes:
  #     - .:/usr/app
  #   depends_on:
  #     - rentx-db
  #   links:
  #     - rentx-db

volumes:
  pgdata:
    driver: local
